In [2]:
import torch

In [3]:
x = torch.tensor([1,2,3]) # n-dimensionale Arrays 
x

tensor([1, 2, 3])

In [4]:
torch.rand(2,3) # Zufallszahlen 

tensor([[0.9950, 0.1129, 0.6031],
        [0.2066, 0.6200, 0.2579]])

In [5]:
torch.zeros(1,2)

tensor([[0., 0.]])

In [6]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x + ones # Addition mit Broadcasting (entlang einer Dimension, bei der es klappt)

tensor([[2., 3., 4.],
        [2., 3., 4.]])

In [14]:
a = torch.tensor([[1., 2], [3,4]])
b = torch.tensor([[5., 6], [7, 8]])
# Matrizenmultiplikation
torch.matmul(a,b)
a @ b 

tensor([[19., 22.],
        [43., 50.]])

In [15]:
a*b # elementenweise 

tensor([[ 5., 12.],
        [21., 32.]])

In [16]:
a.sum()

tensor(10.)

In [17]:
a.mean()

tensor(2.5000)

In [19]:
# cpu, cuda, mps usw. 

if torch.cuda.is_available():
    device = torch.device("cuda")
else: 
    device = torch.device("cpu")

device = torch.device("mps") # für Apple Silicon 
device

device(type='mps')

In [134]:
import torch.nn as nn # Neuronale Netz 
import torch.optim as optim # Optimierer 

# 10 Eingänge, 1 Ausgang -> Fully-Connected feedforward neural network (ohne Hidden)
NN = nn.Linear(10,1) # in Tensorflow -> Dense Wx+b 
# Perceptron, MLP = Multi-Layer Perceptron ("old-school")
# in Publikationen: FC, FNN, FFN, FFNN, FC-FFNN 

loss = nn.MSELoss() # Kostenfunktion, Verlustfunktion
# loss, cost, criterion, crit 
optimizer = optim.SGD(NN.parameters(), lr= 1e-2) # Stochatic Gradient Descent
# lr = Lernrate (eta, alpha); NN.parameters() -> Gewichte + Biases 
input_data = torch.randn(10) # zufällige Daten (X)
output = NN(input_data) # y_pred, y_hat -> Forward-Pass 
y = torch.ones(1) # target, wir möchten, dass NN eine 1 ausgibt -> Realität, y_true, Ground Truth 

loss_out = loss(output, y) # Unterschied zwischen Modell und Realität, Anfangswert der Kostenfunktion 

print(f"Kosten: {loss_out:.2} (vor Update)")

# zwei magischen Zeilen (Gradientenabstiegsmethode in diesem Fall)
loss_out.backward() # Gradienten berechen (Backward-Pass) Backpropagation  
optimizer.step() # Update-Schritt 
output_new = NN(input_data) # bereits mit neuen Gewichten 
loss_new = loss(output_new,y) # Wert der Kostenfunktion nach Update
print(f"Kosten: {loss_new:.2} (nach Update)")



Kosten: 2.0 (vor Update)
Kosten: 1.3 (nach Update)


In [ ]:
x = torch.tensor(2.0, requires_grad=True) # Gradienten mitschleppen während des Forwards 
y = x**2 + 3*x + 5 
# 2*x + 3 -> 2*2.0 + 3 = 7
y.backward() # autograd 
x.grad 

tensor(7.)